import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

// 1. OneSignal Integration
importScripts('https://cdn.onesignal.com/sdks/OneSignalSDKWorker.js');

// 2. Standard PWA Caching
self.skipWaiting()
clientsClaim()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Clean up old caches
cleanupOutdatedCaches()
